Add accessibility testing tools
rebelappstudio/accessibility_tools pull request #46
Opened 2024-03-20 12:29 UTC by aednlaxer

- [x] New example app with code comments for some issues
- [x] Testing tools panel
- [x] Option to control logging level (verbose, warnings, none)
- [ ] README updates
- [ ] Verify changes with the designer

2024-04-05 10:04 UTC, utopicnarwhal requested changes

2024-04-09 09:47 UTC, aednlaxer commented on example/lib/app_localizations.dart
> +class AppLocalizations {
It's created manually to let users play with localizations toggle in the example app. I don't think we need to care much about placing localizations in ARB files

2024-04-09 09:49 UTC, aednlaxer commented on example/lib/main.dart
> +      theme: ThemeData(
I've added a dark theme. I'd like not to add high contrast themes just now. In the future I'd like to have a toggle that changes the high contrast flag, let's add themes then

2024-04-09 09:50 UTC, aednlaxer commented on lib/src/accessibility_tools.dart
> +  late CheckerManager _checker = CheckerManager(
It's just a way to initalize something not `final` later without using the `initState` method

2024-04-09 10:05 UTC, aednlaxer commented on lib/src/accessibility_tools.dart
>      return Stack(
I've played with this and decided not to add it:
1. I'm okay with testing tools using main app's theme even if it's not using M3
2. I'd like to follow user's selected theme (dark or light) for _accessibility_ purposes :) 
 
Adding 
```dart
data: ThemeData(useMaterial3: true),
```
seems to break light-dark theme switching. Creating monsters like

```dart
data: ThemeData.from(
    colorScheme: Theme.of(context).colorScheme,
    useMaterial3: true,
),
```
doesn't seem right

2024-04-24 12:50 UTC, merged